apiVersion: apps/v1
kind: Deployment
metadata:
  name: qa-api-deployment
spec:
  selector:
    matchLabels:
      app: api
  template:
    spec:
      containers:
      - name: api
      imagePullSecrets:
      - name: qa-dockerconfigjson-github-com