apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qa


patchesJson6902:
- path: ingress.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: ingress
    version: v1
  
images:
- name: ghcr.io/symphonygroup/bg-showcase-api
  newName: ghcr.io/symphonygroup/bg-showcase-api
  newTag: 94e996c4767e2c72acd25e7839080cc741d7a355
- name: ghcr.io/symphonygroup/bg-showcase-ui
  newName: ghcr.io/symphonygroup/bg-showcase-ui
  newTag: 3173ca10f1b6e48483b5d31a46cac439d94db5f2
resources:
- ../../base
