apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qa
namePrefix: qa-


patchesJson6902:
- path: ingress.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: ingress
    version: v1
  
images:
- name: ghcr.io/symphonygroup/bg-showcase-api
  newName: ghcr.io/symphonygroup/bg-showcase-api
  newTag: 01939544230d4064745bcf238cbecaf993507199
- name: ghcr.io/symphonygroup/bg-showcase-ui
  newName: ghcr.io/symphonygroup/bg-showcase-ui
  newTag: latest
resources:
- ../../base
