apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qa


patchesJson6902:
- path: ingress.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: ingress
    version: v1
  
images:
- name: ghcr.io/symphonygroup/bg-showcase-api
  newName: ghcr.io/symphonygroup/bg-showcase-api
  newTag: 18babae570c75bcb703656ccfe186d1871422b67
- name: ghcr.io/symphonygroup/bg-showcase-ui
  newTag: cicd
resources:
- ../../base
