apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qa


patchesJson6902:
- path: ingress.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: ingress
    version: v1
  
images:
- name: ghcr.io/symphonygroup/bg-showcase-api
  newName: ghcr.io/symphonygroup/bg-showcase-api
  newTag: 550eccc7be18351931df0cf13bd74a462589ca07
- name: ghcr.io/symphonygroup/bg-showcase-ui
  newName: ghcr.io/symphonygroup/bg-showcase-ui
  newTag: 0fb42351fe3ad54a18a3f3e7208042a7a821b4fe
resources:
- ../../base
