apiVersion: apps/v1
kind: Deployment
metadata:
  name: qa-ui-deployment
spec:
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
      imagePullSecrets:
      - name: qa-dockerconfigjson-github-com