apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-api-deployment
spec:
  selector:
    matchLabels:
      app: api
  template:
    spec:
      containers:
      - name: api
      imagePullSecrets:
      - name: dev-dockerconfigjson-github-com