apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
namePrefix: dev-

patchesJson6902:
- path: ingress.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: ingress
    version: v1

images:
- name: ghcr.io/symphonygroup/bg-showcase-api
  newName: ghcr.io/symphonygroup/bg-showcase-api
  newTag: d3a0b999b6429a1191ff30017689c1252f69cae6
- name: ghcr.io/symphonygroup/bg-showcase-ui
  newName: ghcr.io/symphonygroup/bg-showcase-ui
  newTag: 3646d704812e2210c42750a64fba9439b20d3c82
resources:
- ../../base
