apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-ui-deployment
spec:
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
      imagePullSecrets:
      - name: dev-dockerconfigjson-github-com