apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devspace
namePrefix: devspace-

patchesJson6902:
- path: ingress.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: ingress
    version: v1
- path: configmap.yaml
  target:
    kind: ConfigMap
    name: ui-config
    version: v1

images:
- name: ghcr.io/symphonygroup/bg-showcase-api
  newName: ghcr.io/symphonygroup/bg-showcase-api
  newTag: latest
- name: ghcr.io/symphonygroup/bg-showcase-ui
  newName: ghcr.io/symphonygroup/bg-showcase-ui
  newTag: latest
resources:
- ../../base
