apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: dev
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: symph/api:0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api-clusterip
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
  - name: api
    protocol: TCP
    port: 80
    targetPort: 80