kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: local
  name: postgres-pv-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/dev/postgres-data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: local
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi