apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  namespace: local
spec:
  selector:
    matchLabels:
      app: ui
  replicas: 1
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: ghcr.io/symphonygroup/bg-showcase-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
          - name: ui-volume
            mountPath: /usr/share/nginx/html/config
      imagePullSecrets:
      - name: dockerconfigjson-github-com
      volumes:
        - name: ui-volume
          configMap:
            name: ui-config
---
apiVersion: v1
kind: Service
metadata:
  name: ui-clusterip
  namespace: local
spec:
  type: ClusterIP
  selector:
    app: ui
  ports:
  - name: ui
    protocol: TCP
    port: 80
    targetPort: 80