version: "3.3"

services:
  oauth:
    build:
      dockerfile: ./oauth/Dockerfile
      context: .
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      COGNITO_APP_CLIENT_ID: ${COGNITO_APP_CLIENT_ID}
      COGNITO_OAUTH_CLIENT_SECRET: ${COGNITO_OAUTH_CLIENT_SECRET}
