version: "3.3"

services:
  auth:
    build:
      dockerfile: ./auth/Dockerfile
      context: .
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      COGNITO_APP_CLIENT_ID: ${COGNITO_APP_CLIENT_ID}
      COGNITO_USER_POOL_ID: ${COGNITO_USER_POOL_ID}
      AUD: 3cn1qks1ojhf4qmeh5dil0qhis
  api:
    build:
      dockerfile: ./api/Dockerfile
      context: .
    ports:
      - 8081:8080
    environment:
      PORT: 8080
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      COGNITO_APP_CLIENT_ID: ${COGNITO_APP_CLIENT_ID}
      COGNITO_USER_POOL_ID: ${COGNITO_USER_POOL_ID}
      AUD: 3cn1qks1ojhf4qmeh5dil0qhis
